//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public Nullable<float> Cost { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public int CustomerCount { get; set; }
        public int HotelId { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
    }
}
