//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string Place { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> TotalCapacity { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
