//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int InformationId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Bday { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Phone { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
