//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Bookings = new HashSet<Booking>();
            this.UserInformations = new HashSet<UserInformation>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<UserInformation> UserInformations { get; set; }
        public virtual webpages_UsersInRoles webpages_UsersInRoles { get; set; }
        public virtual webpages_UsersInRoles webpages_UsersInRoles1 { get; set; }
        public virtual webpages_UsersInRoles webpages_UsersInRoles2 { get; set; }
    }
}
